//! Circom witness generator for the RISC0 STARK verifier circuit.
//!
//! Takes the Circom witness calculation graph (.bin) and the input JSON (seal)
//! and produces a .wtns (witness) file that can be loaded by the gnark pipeline.
//!
//! Usage:
//!   risc0-witness-gen --graph <graph.bin> --input <seal_input.json> --output <witness.wtns>
//!
//! The graph.bin is located at:
//!   ~/.risc0/extensions/v0.1.0-risc0-groth16/stark_verify_graph.bin
//!
//! The seal_input.json is generated by the RISC0 host with --export-seal.

use anyhow::{Context, Result};
use clap::Parser;
use std::io::Cursor;
use std::path::PathBuf;

#[derive(Parser, Debug)]
#[command(author, version, about = "Circom witness generator for RISC0 STARK verifier")]
struct Args {
    /// Path to the Circom witness calculation graph (.bin).
    #[arg(long)]
    graph: PathBuf,

    /// Path to the input JSON (seal data).
    #[arg(long)]
    input: PathBuf,

    /// Path to write the .wtns output.
    #[arg(long)]
    output: PathBuf,

    /// Also export the witness as a JSON file (decimal strings).
    #[arg(long)]
    export_json: Option<PathBuf>,
}

fn main() -> Result<()> {
    let args = Args::parse();

    eprintln!("Loading graph from: {}", args.graph.display());
    let graph = std::fs::read(&args.graph)
        .with_context(|| format!("Failed to read graph file: {}", args.graph.display()))?;
    eprintln!("Graph loaded: {} bytes", graph.len());

    eprintln!("Loading input from: {}", args.input.display());
    let inputs = std::fs::read_to_string(&args.input)
        .with_context(|| format!("Failed to read input file: {}", args.input.display()))?;
    eprintln!("Input loaded: {} bytes", inputs.len());

    eprintln!("Calculating witness...");
    let start = std::time::Instant::now();
    let witness_encoded = circom_witnesscalc::calc_witness(&inputs, &graph)
        .map_err(|e| anyhow::anyhow!("Witness calculation failed: {}", e))?;
    let elapsed = start.elapsed();
    eprintln!("Witness calculated in {:.2?}", elapsed);

    // Write raw .wtns file.
    std::fs::write(&args.output, &witness_encoded)
        .with_context(|| format!("Failed to write witness: {}", args.output.display()))?;
    eprintln!("Witness written to: {} ({} bytes)", args.output.display(), witness_encoded.len());

    // Parse the .wtns to report stats and optionally export JSON.
    let wtns: wtns_file::WtnsFile<32> = wtns_file::WtnsFile::read(Cursor::new(&witness_encoded))
        .context("Failed to parse witness file")?;
    eprintln!("Witness has {} values", wtns.witness.0.len());

    // Export as JSON if requested.
    if let Some(json_path) = args.export_json {
        let values: Vec<String> = wtns.witness.0.iter().map(|fe| {
            // FieldElement<32> is 32 bytes in LE. Convert to decimal.
            let bytes = fe.as_bytes();
            let val = num_bigint::BigUint::from_bytes_le(bytes);
            val.to_str_radix(10)
        }).collect();

        let json = serde_json::to_string_pretty(&values)
            .context("Failed to serialize witness to JSON")?;
        std::fs::write(&json_path, json)
            .with_context(|| format!("Failed to write JSON: {}", json_path.display()))?;
        eprintln!("Witness JSON written to: {}", json_path.display());
    }

    eprintln!("Done!");
    Ok(())
}
